version: '3'

services:
    ead-authuser-db:
        image: postgres:13.2-alpine
        container_name: ead-authuser-db
        network_mode: host
        restart: always
        tty: true
        environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=ead-authuser
        - POSTGRES_DB=ead-authuser
